### ISSUE TITLE
Const collections of structs contain dicts instead

### ISSUE THREAD

**Issue by soaxelbrooke** [unmade/thrift-pyi#48]
The following thrift:

```thrift
namespace scala test

struct Foo {
    1: required string bar
    2: required i64 baz
}

const list<Foo> foo = [
    {
        "bar": "value",
        "baz": 1234
    }
]
```

Produces the following python:

```python
from dataclasses import dataclass
from typing import *

foo: List[Dict[str, str]] = [{"bar": "value", "baz": 1234}]

@dataclass
class Foo:
    bar: str
    baz: int
```

Which means that importing modules need to parse the imported const into a `list<Foo>` themselves.

**Comment by unmade** [comment]
I'm afraid this one would be impossible to fix due to how `thriftpy2` parses the module. If we load your example and looks into metadata it parsed as follows:

```python
defaultdict(
    list,
    {
        'structs': [dates.Foo],
        'consts': [
            Foo(bar='value', baz=1234),
            [{'bar': 'value', 'baz': 1234}]
        ]
    }
)
```

That means that in Python the list items are of type `dict` and you would access properties on each object as follows:

```python
module = thriftpy2.load("test.thrift")
module.foo[0]["bar"]
```


Let me know if you have any ideas on that

**Comment by soaxelbrooke** [comment]
Thanks, sorry for the late reply. I don't have any suggestions currently, but will let you know if inspiration strikes.

**Comment by unmade** [comment]
No worries! Please feel free to re-open if anything
